services:
  auth-service:
    environment:
      - NODE_ENV=development
    volumes:
      - ./auth-server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  board-service-1:
    environment:
      - NODE_ENV=development
    volumes:
      - ./board-server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  board-service-2:
    environment:
      - NODE_ENV=development
    volumes:
      - ./board-server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  board-service-3:
    environment:
      - NODE_ENV=development
    volumes:
      - ./board-server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev